flowchart LR
    subgraph PP[Pod：推荐编排]
        P[容器：PaiRec<br/>进程：推荐程序]
    end
    subgraph SP[Pod：稀疏召回]
        S[容器：稀疏召回<br/>进程：召回程序]
    end
    subgraph OP[Pod：文档检索数据库]
        O[容器：OpenSearch<br/>进程：OpenSearch JVM]
    end
    P <-->|bRPC| S
    S <-->|HTTP| O
